# Generated by Django 4.2.3 on 2023-09-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookahotelname', models.CharField(max_length=150)),
                ('bookahotelage', models.IntegerField(max_length=30)),
                ('bookahotelcitizenship', models.CharField(max_length=150)),
                ('bookachosenhotel', models.CharField(max_length=150)),
                ('bookahoteldescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactname', models.CharField(max_length=150)),
                ('contactsurname', models.CharField(max_length=150)),
                ('contactage', models.IntegerField(max_length=30)),
                ('contactcitizenship', models.CharField(max_length=150)),
                ('contactdescription', models.TextField()),
            ],
        ),
    ]
